POST http://localhost:3301/posts
Content-Type: application/json

{
    "publicationDate": "10/04/2026",
    "postContent": "Meu primeiro post",
    "likeNumbers": 350
}

###

GET http://localhost:3301/posts

###

PUT http://localhost:3301/posts/        
Content-Type: application/json

{
    "publicationDate": "24/04/2026",
    "postContent": "Atualizando meu primeiro post: Na verdade...",
    "likeNumbers": 576
}

###

DELETE http://localhost:3301/posts/
